#
# Makefile for native language support
#

obj-$(CONFIG_NLS)		+= nls_base.o

obj-$(CONFIG_NLS_CODEPAGE_437)	+= nls_cp437.o
obj-$(CONFIG_NLS_CODEPAGE_936)	+= nls_cp936.o
obj-$(CONFIG_NLS_ASCII)		+= nls_ascii.o
obj-$(CONFIG_NLS_ISO8859_1)	+= nls_iso8859-1.o
obj-$(CONFIG_NLS_UTF8)		+= nls_utf8.o
